spring:
  application:
    name: aws-qna

  datasource:
    url: jdbc:mysql://localhost:3306/quizdb?useSSL=false&allowPublicKeyRetrieval=true
    username: quizuser
    password: quizpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

questions:
  list:
    - deployment.json
    - development.json
    - examOne.json
    - examTwo.json
    - examThree.json
    - security.json
    - troubleshooting.json
    - itExpert.json


logging:
  hibernate:
    level: debug